name = "Terran Exile"
mc_version = "1.20.2"

[jar]
type = "paper"

[variables]
PORT = "25565"

[launcher]
preset_flags = "aikars"
proxy_flags = false
nogui = true
eula_args = false

[[plugins]]
type = "jenkins"
url = "https://ci.citizensnpcs.co"
job = "Denizen_Developmental"
build = "latest"
artifact = "first"

[[plugins]]
type = "jenkins"
url = "https://ci.citizensnpcs.co"
job = "Citizens2"
build = "latest"
artifact = "first"

[[plugins]]
type = "modrinth"
id = "simple-voice-chat"
version = "b2fQucaC"

[markdown]
files = ["README.md"]
auto_update = false
