name = "Terran Exile"
mc_version = "1.20.2"

[jar]
type = "paper"

[variables]
PORT = "25565"

[launcher]
nogui = true
preset_flags = "aikars"

[[plugins]]
type = "jenkins"
url = "https://ci.citizensnpcs.co"
job = "Denizen_Developmental"
build = "latest"
artifact = "first"

[[plugins]]
type = "jenkins"
url = "https://ci.citizensnpcs.co"
job = "Citizens2"
build = "latest"
artifact = "first"

[[plugins]]
type = "modrinth"
id = "simple-voice-chat"
version = "b2fQucaC"

[[plugins]]
type = "url"
url = "https://download.luckperms.net/1521/bukkit/loader/LuckPerms-Bukkit-5.4.108.jar"
filename = "LuckPerms-Bukkit-5.4.108.jar"
desc = "LuckPerms"

[markdown]
files = ["README.md"]
auto_update = false

[options]
upload_to_mclogs = false
